apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-repo-microservices
spec:
  selector:
    matchLabels:
      app: nestjs-repo-microservices
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-repo-microservices
    spec:
      containers:
        - name: nestjs-repo-microservices
          image: danxc/nestjs-repo-microservices
          ports:
            - containerPort: 3000